name: Energy Aware CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run pytest inside eco-ci container
        id: runenergy
        uses: green-coding-berlin/eco-ci-energy-estimation@v3
        with:
          task: run-workload
          workload-command: pytest

      - name: Save eco report
        run: echo "${{ steps.runenergy.outputs.measurement }}" > eco_report.json

      - name: Upload eco report artifact
        uses: actions/upload-artifact@v4
        with:
          name: eco-report
          path: eco_report.json
