name: Energy Aware CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      # Start energy measurement
      - name: Start measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v3
        with:
          task: start-measurement

      # Get energy results
      - name: Get results
        id: energy
        uses: green-coding-berlin/eco-ci-energy-estimation@v3
        with:
          task: get-measurement

      # Save result as file
      - name: Save eco report
        run: echo "${{ steps.energy.outputs.measurement }}" > eco_report.json

      # Upload artifact
      - name: Upload eco report artifact
        uses: actions/upload-artifact@v4
        with:
          name: eco-report
          path: eco_report.json
