name: Energy Aware CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: pip install -r requirements.txt

      # REQUIRED: Docker must be running
      - name: Start Docker
        run: |
          sudo systemctl start docker
          sudo docker info

      # ðŸŸ© Run pytest INSIDE the measurement container
      - name: Measure energy while running tests
        id: eco
        uses: green-coding-berlin/eco-ci-energy-estimation@v3
        with:
          task: run-command
          command: "pytest --maxfail=1 --disable-warnings -q"

      # Save JSON report
      - name: Save eco report
        run: echo '${{ steps.eco.outputs.measurement }}' > eco_report.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eco-report
          path: eco_report.json
          retention-days: 30
