name: Energy Aware CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: pip install -r requirements.txt

      # Step 1: Start measurement
      - name: Start energy measurement
        id: start
        uses: green-coding-berlin/eco-ci-energy-estimation@v3
        with:
          task: start-measurement

      # Step 2: Run pytest normally
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      # Step 3: Get measurement
      - name: Get energy results
        id: result
        uses: green-coding-berlin/eco-ci-energy-estimation@v3
        with:
          task: get-measurement

      # Step 4: Save JSON to file
      - name: Save eco report
        run: echo '${{ steps.result.outputs.measurement }}' > eco_report.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eco-report
          path: eco_report.json
